#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-sphinxcontrib_plantuml
Version  : 0.24.1
Release  : 15
URL      : https://files.pythonhosted.org/packages/ce/71/537416c26f4b3c474ab8d91f808a0b522de7bc799d776cac01b96f37e463/sphinxcontrib-plantuml-0.24.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/ce/71/537416c26f4b3c474ab8d91f808a0b522de7bc799d776cac01b96f37e463/sphinxcontrib-plantuml-0.24.1.tar.gz
Summary  : Sphinx "plantuml" extension
Group    : Development/Tools
License  : BSD-2-Clause
Requires: pypi-sphinxcontrib_plantuml-license = %{version}-%{release}
Requires: pypi-sphinxcontrib_plantuml-python = %{version}-%{release}
Requires: pypi-sphinxcontrib_plantuml-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(sphinx)

%description
PlantUML for Sphinx
===================
Installation
------------
.. code-block::

%package license
Summary: license components for the pypi-sphinxcontrib_plantuml package.
Group: Default

%description license
license components for the pypi-sphinxcontrib_plantuml package.


%package python
Summary: python components for the pypi-sphinxcontrib_plantuml package.
Group: Default
Requires: pypi-sphinxcontrib_plantuml-python3 = %{version}-%{release}

%description python
python components for the pypi-sphinxcontrib_plantuml package.


%package python3
Summary: python3 components for the pypi-sphinxcontrib_plantuml package.
Group: Default
Requires: python3-core
Provides: pypi(sphinxcontrib_plantuml)
Requires: pypi(sphinx)

%description python3
python3 components for the pypi-sphinxcontrib_plantuml package.


%prep
%setup -q -n sphinxcontrib-plantuml-0.24.1
cd %{_builddir}/sphinxcontrib-plantuml-0.24.1
pushd ..
cp -a sphinxcontrib-plantuml-0.24.1 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1668788880
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 setup.py build

popd
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-sphinxcontrib_plantuml
cp %{_builddir}/sphinxcontrib-plantuml-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/pypi-sphinxcontrib_plantuml/5c221dd41aba870a4599f86efecaaa7171b4138f || :
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -tt setup.py build install --root=%{buildroot}-v3
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-sphinxcontrib_plantuml/5c221dd41aba870a4599f86efecaaa7171b4138f

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
