#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: pyproject
#
Name     : pypi-sphinxcontrib_plantuml
Version  : 0.26
Release  : 18
URL      : https://files.pythonhosted.org/packages/51/76/df35c9091e794ac3421070273115a858b35806afdffacb7014c6ec171ab4/sphinxcontrib-plantuml-0.26.tar.gz
Source0  : https://files.pythonhosted.org/packages/51/76/df35c9091e794ac3421070273115a858b35806afdffacb7014c6ec171ab4/sphinxcontrib-plantuml-0.26.tar.gz
Summary  : Sphinx "plantuml" extension
Group    : Development/Tools
License  : BSD-2-Clause
Requires: pypi-sphinxcontrib_plantuml-license = %{version}-%{release}
Requires: pypi-sphinxcontrib_plantuml-python = %{version}-%{release}
Requires: pypi-sphinxcontrib_plantuml-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(setuptools)
BuildRequires : pypi(wheel)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
PlantUML for Sphinx
===================
Installation
------------
.. code-block::

%package license
Summary: license components for the pypi-sphinxcontrib_plantuml package.
Group: Default

%description license
license components for the pypi-sphinxcontrib_plantuml package.


%package python
Summary: python components for the pypi-sphinxcontrib_plantuml package.
Group: Default
Requires: pypi-sphinxcontrib_plantuml-python3 = %{version}-%{release}

%description python
python components for the pypi-sphinxcontrib_plantuml package.


%package python3
Summary: python3 components for the pypi-sphinxcontrib_plantuml package.
Group: Default
Requires: python3-core
Provides: pypi(sphinxcontrib_plantuml)
Requires: pypi(sphinx)

%description python3
python3 components for the pypi-sphinxcontrib_plantuml package.


%prep
%setup -q -n sphinxcontrib-plantuml-0.26
cd %{_builddir}/sphinxcontrib-plantuml-0.26
pushd ..
cp -a sphinxcontrib-plantuml-0.26 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1693253864
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -m build --wheel --skip-dependency-check --no-isolation

popd

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-sphinxcontrib_plantuml
cp %{_builddir}/sphinxcontrib-plantuml-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/pypi-sphinxcontrib_plantuml/5c221dd41aba870a4599f86efecaaa7171b4138f || :
pip install --root=%{buildroot} --no-deps --ignore-installed dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
pip install --root=%{buildroot}-v3 --no-deps --ignore-installed dist/*.whl
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-sphinxcontrib_plantuml/5c221dd41aba870a4599f86efecaaa7171b4138f

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
