#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-sphinxcontrib_plantuml
Version  : 0.23
Release  : 3
URL      : https://files.pythonhosted.org/packages/db/32/e224f540b4a813d93718b633b7b6fa8298047c120122a75d6f98880bf7be/sphinxcontrib-plantuml-0.23.tar.gz
Source0  : https://files.pythonhosted.org/packages/db/32/e224f540b4a813d93718b633b7b6fa8298047c120122a75d6f98880bf7be/sphinxcontrib-plantuml-0.23.tar.gz
Summary  : Sphinx "plantuml" extension
Group    : Development/Tools
License  : BSD-2-Clause
Requires: pypi-sphinxcontrib_plantuml-license = %{version}-%{release}
Requires: pypi-sphinxcontrib_plantuml-python = %{version}-%{release}
Requires: pypi-sphinxcontrib_plantuml-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(sphinx)

%description
PlantUML for Sphinx
===================
Installation
------------
.. code-block::

%package license
Summary: license components for the pypi-sphinxcontrib_plantuml package.
Group: Default

%description license
license components for the pypi-sphinxcontrib_plantuml package.


%package python
Summary: python components for the pypi-sphinxcontrib_plantuml package.
Group: Default
Requires: pypi-sphinxcontrib_plantuml-python3 = %{version}-%{release}

%description python
python components for the pypi-sphinxcontrib_plantuml package.


%package python3
Summary: python3 components for the pypi-sphinxcontrib_plantuml package.
Group: Default
Requires: python3-core
Provides: pypi(sphinxcontrib_plantuml)
Requires: pypi(sphinx)

%description python3
python3 components for the pypi-sphinxcontrib_plantuml package.


%prep
%setup -q -n sphinxcontrib-plantuml-0.23
cd %{_builddir}/sphinxcontrib-plantuml-0.23

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1646064695
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-sphinxcontrib_plantuml
cp %{_builddir}/sphinxcontrib-plantuml-0.23/LICENSE %{buildroot}/usr/share/package-licenses/pypi-sphinxcontrib_plantuml/5c221dd41aba870a4599f86efecaaa7171b4138f
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-sphinxcontrib_plantuml/5c221dd41aba870a4599f86efecaaa7171b4138f

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
